### ISSUE TITLE
ERROR:drafthorse:'/OutputIntents'

### ISSUE THREAD

**Issue by JustinGuese** [pretix/python-drafthorse#46]
when using the example code from the readme on a PDF/a3 compliant PDF, I am getting the error
ERROR:drafthorse:'/OutputIntents'

any ideas?

**Comment by JustinGuese** [comment]
colab example: 
https://colab.research.google.com/drive/1kVs6DEBRwMmGo5Ykf9KpK_glrBb0fJyi?usp=sharing

**Comment by wiffbi** [comment]
In your example, is output.pdf still generated? The ERROR should only show up in logs, but should not hinder generation of the PDF. The problem is, that your example PDF from https://pdfobject.com/pdf/sample.pdf does not have any `/OutputIntents` defined, which then causes this log.error. The PDF should be generated nonetheless.

One could argue that it should not log an error, but a warning?

**Comment by JustinGuese** [comment]
yes, indeed it generated the PDF thanks for the library :)
